### PR TITLE
Rebase on upstream 2.5.x

### PR DESCRIPTION
**Pull request by olivierkeke**
Hi @nokyyz,
I rebased your work on branch 2.5.x.

### CODE REVIEW

**Comment by nokyyz** [comment]
@olivierkeke Hi Olivier, I can't merge your PR due to merge conflicts. Have you pull the last changes in my repository before merging with the latest Openhab version ?

**Comment by olivierkeke** [comment]
@nokyyz Yes I've made a `git rebase` of your last version on the last upstream 2.5.x branch. Since it's a rebase and not a merge the git history is modified, that's why you can't auto merge it...
Three options:
- Can you force the update of master with `git push --force`? Don't know if it's permitted on master...
- Keep the branch separated from mater (I think this branch can be auto merged with upstream 2.5.x)
- I do it again with a merge instead of rebase.

**Comment by olivierkeke** [comment]
see #15

**Comment by nokyyz** [comment]
Thx !

**Pull request closed without merging**
